name: CI

on: [pull_request, push]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typescript:
    name: TypeScript
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - run: npm ci

    - run: npm run lint

    - run: npm run package --scripts-prepend-node-path
